package com.myspace.kafalaserviceid;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class employee implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public employee() {
    }

// test comment after change


}
